config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  root 'books#index'
  #get 'books'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books
end

app/models/user.rb
class User < ApplicationRecord
	has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: [:show, :edit, :update, :destroy]
	before_action :find_categories, only: [:new, :edit]
	before_action :find_category_id_for_book, only: [:create, :update]

	def index
		if params[:category].blank?
			@books = Book.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@books = Book.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def show
	end

	def new
		#@book = Book.new
		@book = current_user.books.build
		#@categories = Category.all.map{|c| [c.name, c.id]}
	end

	def create
		#@book = Book.new(book_params)
		@book = current_user.books.build(book_params)
		#@book.category_id = params[:category_id]

		if @book.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @book.update(book_params)
			redirect_to book_path(@book)
		else
			render 'new'
		end
	end

	def destroy
		@book.destroy
		redirect_to root_path
	end

	private
		def book_params
			#params.require(:book).permit(:title, :description, :author)
			params.require(:book).permit(:title, :description, :author, :category_id)
		end

		def find_book
			@book = Book.find(params[:id])
		end

		def find_categories
			@categories = Category.all.map{|c| [c.name, c.id]}
		end

		def find_category_id_for_book
			@book.category_id = params[:category_id]
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
<!-- added later -->
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a catagory") %>

<!-- added at the begining -->
  <%= f.input :title, label: "Book Title" %>
  <%= f.input :description%>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
  <%= f.select :category_id, @categories %>
  <%= f.input :title, label: "Book Title" %>
  <%= f.input :description%>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>

app/views/books/index.html.erb
<h1 class="current-category"><%= params[:category]%></h1>

<% if @books.count == 0 %>
	<h1>There are no books currently in this category</h1>
<% else %>
	<% @books.each do |book| %>
  		<h2><%= link_to book.title, book_path(book) %></h2>
	<% end %>
<% end %>


<!--
<%= link_to "Add Book", new_book_path %>
-->

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<h2><%= @book.title %></h2>
<h3><%= @book.author %></h3>
<h4>Catagory: <%= @book.category.name %></h4>
<p><%= @book.description %></p>

<%= link_to "Back", root_path %>

<!--# To avoid problems when there is no user signed in -->

<% if user_signed_in? %>
	<% if @book.user_id == current_user.id %>
		<%= link_to "Edit", edit_book_path(@book) %>
		<%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you sure?" } %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="cointainer">
        <div class="navbar-header">
          <%= link_to "Book Review", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>

          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
          <% end %>

        </ul>

        <ul class="nav navbar-nav navbar-right">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" area-expanded="false">Catagories <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Category.all.each do |category| %>
                <li class="<%= 'active' if params[:category] == category.name %>">
                  <%= link_to category.name, books_path(category: category.name), class:"link" %>
                </li>
              <% end %>
            </ul>

          </li>

          <% if user_signed_in? %>
            <li><%= link_to "Add Book", new_book_path %></li>
          <% end %>
        </ul>

      </div>
    </nav>

    <p class="notice"><%= notice %></p>
	  <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>